### ISSUE TITLE
ERP - Upgrading Xamarin.Forms from v4.7 to v4.8 introduces duplicate menu items.

### ISSUE THREAD

**Issue by m1dst** [telerik/telerik-xamarin-forms-samples#102]
Running on IOS or Android with v4.7 of Xamarin.Forms produces a UI like this...

![image](https://user-images.githubusercontent.com/958968/91038160-3adb6000-e602-11ea-8a9c-242cba6f2d5d.png)

Simply upgrading to 4.8 via nuget and starting the app you see the same UI.

![image](https://user-images.githubusercontent.com/958968/91038197-4af33f80-e602-11ea-9ae5-18a5a948d07d.png)

Great.

Close the app with the home button and reopen it again.

The UI is initially the same but after a second or so changes to..

![image](https://user-images.githubusercontent.com/958968/91038900-7d516c80-e603-11ea-8f4d-3007409f94a3.png)

If you click more you see...

![image](https://user-images.githubusercontent.com/958968/91038944-922e0000-e603-11ea-9551-6b749b16dc1e.png)

Looks like the menu is being built twice.

It also produces many ambiguous references that need to be fixed before it will compile.

'PresentationMode' is an ambiguous reference between 'ErpApp.Models.PresentationMode' and 'Xamarin.Forms.PresentationMode'

**Comment by PavelRPavlov** [comment]
The issue is also reported to the MvvmCross framework:
https://github.com/MvvmCross/MvvmCross/issues/3896

**Comment by PavelRPavlov** [comment]
@m1dst Thank you for turning our attention to this issue. I looked into it and it seems to be caused by a change in Xamarin.Forms which in tern causes a change in the MvvmCross framework. 

The ERP app entirely depends on the navigation functionality provided by the MvvmCross framework. We do not have any customizations applied and this is why we do not have direct control over how the navigation works. 
I was able to isolate the reported issue in a sample project and opened a bug report to the MvvmCross. Till we wait for their input I have applied a fix in the ERP app which resolves the reported behavior. It is important to note that in my tests I was not able to reproduce the issue on Android. However, in iOS the issue was reproduced every time I tried.

May I please ask you to fetch the latest changes in our development branch and test if the fix resolves the issue on Android as well?

**Comment by m1dst** [comment]
Great.  Just tested and it works OK for me in both IOS and Android.  I can't repro the Android issue so assume it was something I introduced whilst experimenting with it.   Just going to update all the NuGet packages and confirm it still behaves.

**Comment by m1dst** [comment]
Upgraded everything and the dupe items still do not appear.  Curious to hear back from MvvmCross as to why it happened but for now this fix seems to help.
